# Generated by Django 3.1.2 on 2021-03-10 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_auto_20210310_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='bike_id',
            new_name='bike',
        ),
        migrations.AddField(
            model_name='notes',
            name='writer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
