# Generated by Django 3.1.2 on 2021-03-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_bike_bike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='bike_name',
            new_name='model',
        ),
    ]
