# Generated by Django 3.1.2 on 2021-03-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210310_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='bike',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pages.bike'),
            preserve_default=False,
        ),
    ]
