# Generated by Django 3.1.2 on 2021-03-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210310_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='cost',
        ),
    ]
